name: Проверка
on: [push]
jobs:
  linter_hw1:
    name: Линтер HW1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.1.0 wemake-python-styleguide==0.18.0 bandit==1.7.5
    - name: Flake8
      run: flake8 .
  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.2
        pip install numpy
    - name: Pytest
      run: |
        cd hw1
        python3 -m pytest
  linter_hw3:
    name: Линтер HW3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Dependencies installtion
      run: |
        python -m pip install --upgrade pip
        pip install flake8==7.0.0 wemake-python-styleguide==0.18.0 bandit==1.7.7
    - name: Flake8
      run: |
        cd hw3
        flake8
  tests_for_hw3:
    name: Тесты hw3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Pytest
      run: |
        cd hw3
        python3 -m pytest
